name: racecar-coding
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - scipy
  - sympy
  - plotly
  - pip
  - pip:
    - jupytext
    - nbgitpuller
    - jupyter_contrib_nbextensions
